# Numpy

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

### One dimensional array 

In [3]:
arr = np.array(my_list)

array([1, 2, 3])

## Two dimensional array 
    มีกว้าง ยาว Matrix
    one or two ดู [] เวลา print ว่ามีกี่ตัว

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# List arange(เริ่ม,สุด,เพิ่มทีละ)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
# List ของ 0 กว้าง 2 ยาว 5 
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# eye ออกมาเป็น square
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
# random 0-1 โดยมี 16 ตัว

rand = np.random.rand(16)
rand

array([0.42928536, 0.57997592, 0.48860673, 0.86767108, 0.44055574,
       0.69511149, 0.30565769, 0.36586247, 0.94993515, 0.79852111,
       0.69201618, 0.42922978, 0.8455873 , 0.14873295, 0.88321468,
       0.09287837])

In [67]:
# หา Max Min , indexMax , indexMin ใน array 
print(rand.max())
print(rand.min())


0.9370556792488074
0.07427353066288955


In [68]:
print(rand.argmax())
print(rand.argmin())

11
2


In [59]:
 #สร้าง Arrays ที่ random int (ต่ำสุด,สูงสุด,จำนวน)
rand1 = np.random.randint(0,50,16)
rand1

array([20,  2, 19, 38,  5, 34, 32, 28,  4, 10,  4, 26, 32, 10, 41, 17])

In [78]:
# เปลี่ยนขนาดให้เป็น 2 d โดยขนาดคูณกันต้องตรงกัน 
rand2 = rand1.reshape(4,4)

In [81]:
rand2

array([[20,  2, 19, 38],
       [ 5, 34, 32, 28],
       [ 4, 10,  4, 26],
       [32, 10, 41, 17]])

In [79]:
# ดู shape (มีเลขเดียวเป็น 1 d , มี2 เลขเป็น 2d มี กว้าง x ยาว)
print(rand1.shape)
print(rand2.shape)

(16,)
(4, 4)


## INDEXING and SELECTION

In [83]:
arr = np.arange(0,10)

In [ ]:
arr

In [85]:
# Slice arrays เหมือน list 
arr[1:5]

array([1, 2, 3, 4])

In [87]:
# จะเปลี่ยน arr original ด้วย ไม่ copy arrays
slice_of_arr = arr[2:5]
slice_of_arr[0:4] = 99
slice_of_arr

array([99, 99, 99])

In [88]:
arr

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9])

In [89]:
#ถ้าจะ copy ต้องใช้ คำสั่ง copy 
arr_copy = arr.copy() 

In [90]:
arr_copy

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9])

In [92]:
arr_copy[:2] = 101
print(arr)
print(arr_copy)

[ 0  1 99 99 99  5  6  7  8  9]
[101 101  99  99  99   5   6   7   8   9]


In [3]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [4]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [8]:
# ดึงข้อมูลใน array [row,column ]
arr_2d[0,1]
arr_2d[:2 , 2:]

array([[15],
       [30]])

## Condition in Arrays

In [9]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
boo_arr = arr > 5

In [12]:
boo_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [13]:
arr[boo_arr]

array([ 6,  7,  8,  9, 10])

In [14]:
arr[arr < 3]

array([0, 1, 2])

## Numpy Operation

In [15]:
import numpy as np

In [19]:
arr = np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#เอาค่าใน array +-*/ กันในแต่ละตำแหน่ง 
print(arr + arr)
print(arr - arr)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]


In [24]:
# เอาแต่ละตำแหน่งมา +-*/ กันกับตัวเลข
arr + 100 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])